package fpf

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/m0n0x41d/quint-code/assurance"
	"github.com/m0n0x41d/quint-code/db"
	"github.com/m0n0x41d/quint-code/logger"
)

func (t *Tools) InitProject() error {
	dirs := []string{
		"evidence",
		"decisions",
		"sessions",
		"agents",
	}

	for _, d := range dirs {
		path := filepath.Join(t.GetFPFDir(), d)
		if err := os.MkdirAll(path, 0755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(path, ".gitkeep"), []byte(""), 0644); err != nil {
			return fmt.Errorf("failed to write .gitkeep file: %v", err)
		}
	}

	if t.DB == nil {
		dbPath := filepath.Join(t.GetFPFDir(), "quint.db")
		database, err := db.NewStore(dbPath)
		if err != nil {
			logger.Warn().Err(err).Msg("failed to init DB")
		} else {
			t.DB = database
		}
	}

	return nil
}

func (t *Tools) RecordContext(vocabulary, invariants string) (string, error) {
	return t.RecordContextFromProject(ProjectContext{
		Vocabulary: vocabulary,
		Invariants: invariants,
	})
}

func (t *Tools) RecordContextFromProject(pCtx ProjectContext) (string, error) {
	path := filepath.Join(t.GetFPFDir(), "context.md")

	existingCustomNotes := t.extractCustomNotes(path)

	var sb strings.Builder
	sb.WriteString("<!-- ATTENTION: This file is auto-generated by quint_internalize.\n")
	sb.WriteString("     DO NOT EDIT DIRECTLY - changes will be overwritten.\n")
	sb.WriteString("     Use quint_internalize(remember/forget/overwrite) to modify. -->\n\n")
	sb.WriteString("# Bounded Context\n\n")

	if pCtx.Overview != "" {
		sb.WriteString("## Overview\n\n")
		sb.WriteString(pCtx.Overview)
		sb.WriteString("\n\n")
	}

	if len(pCtx.TechStack) > 0 {
		sb.WriteString("## Tech Stack\n\n")
		for _, tech := range pCtx.TechStack {
			sb.WriteString(fmt.Sprintf("- %s\n", tech))
		}
		sb.WriteString("\n")
	}

	if len(pCtx.Structure) > 0 {
		sb.WriteString("## Structure\n\n")
		for _, s := range pCtx.Structure {
			sb.WriteString(fmt.Sprintf("- %s\n", s))
		}
		sb.WriteString("\n")
	}

	if len(pCtx.DRRInvariants) > 0 {
		sb.WriteString("## Invariants (from DRRs)\n\n")
		for _, inv := range pCtx.DRRInvariants {
			sb.WriteString(fmt.Sprintf("- %s\n", inv))
		}
		sb.WriteString("\n")
	}

	if len(pCtx.DRRAntiPatterns) > 0 {
		sb.WriteString("## Anti-Patterns (from DRRs)\n\n")
		for _, ap := range pCtx.DRRAntiPatterns {
			sb.WriteString(fmt.Sprintf("- %s\n", ap))
		}
		sb.WriteString("\n")
	}

	if pCtx.Vocabulary != "" {
		sb.WriteString("## Vocabulary\n\n")
		sb.WriteString(formatVocabulary(pCtx.Vocabulary))
		sb.WriteString("\n\n")
	}

	if pCtx.Invariants != "" {
		sb.WriteString("## Legacy Invariants\n\n")
		sb.WriteString(formatInvariants(pCtx.Invariants))
		sb.WriteString("\n\n")
	}

	sb.WriteString("## Custom Notes\n\n")
	if existingCustomNotes != "" {
		sb.WriteString(existingCustomNotes)
	} else {
		sb.WriteString("*Add project-specific notes here. This section is preserved across regenerations.*\n")
	}
	sb.WriteString("\n")

	if err := os.WriteFile(path, []byte(sb.String()), 0644); err != nil {
		return "", err
	}
	return path, nil
}

func (t *Tools) extractCustomNotes(path string) string {
	content, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	lines := strings.Split(string(content), "\n")
	inCustomNotes := false
	var notes []string

	for _, line := range lines {
		if strings.HasPrefix(line, "## Custom Notes") {
			inCustomNotes = true
			continue
		}
		if inCustomNotes {
			if strings.HasPrefix(line, "## ") {
				break
			}
			notes = append(notes, line)
		}
	}

	result := strings.TrimSpace(strings.Join(notes, "\n"))
	if result == "*Add project-specific notes here. This section is preserved across regenerations.*" {
		return ""
	}
	return result
}

func formatVocabulary(vocab string) string {
	termPattern := regexp.MustCompile(`([A-Z][a-zA-Z0-9_\[\],<>]+):\s*`)
	matches := termPattern.FindAllStringSubmatchIndex(vocab, -1)

	if len(matches) == 0 {
		return vocab
	}

	var lines []string
	for i, match := range matches {
		termStart := match[2]
		termEnd := match[3]
		defStart := match[1]

		var defEnd int
		if i+1 < len(matches) {
			defEnd = matches[i+1][0]
		} else {
			defEnd = len(vocab)
		}

		term := vocab[termStart:termEnd]
		def := strings.TrimSpace(vocab[defStart:defEnd])

		lines = append(lines, fmt.Sprintf("- **%s**: %s", term, def))
	}

	return strings.Join(lines, "\n")
}

func formatInvariants(inv string) string {
	numPattern := regexp.MustCompile(`(\d+)\.\s+`)
	matches := numPattern.FindAllStringSubmatchIndex(inv, -1)

	if len(matches) == 0 {
		return inv
	}

	var lines []string
	for i, match := range matches {
		numStart := match[2]
		numEnd := match[3]
		contentStart := match[1]

		var contentEnd int
		if i+1 < len(matches) {
			contentEnd = matches[i+1][0]
		} else {
			contentEnd = len(inv)
		}

		num := inv[numStart:numEnd]
		content := strings.TrimSpace(inv[contentStart:contentEnd])

		lines = append(lines, fmt.Sprintf("%s. %s", num, content))
	}

	return strings.Join(lines, "\n")
}

func (t *Tools) RunDecay(ctx context.Context) error {
	defer t.RecordWork("RunDecay", time.Now())
	if t.DB == nil {
		return ErrDatabaseNotInitialized
	}
	ids, err := t.DB.ListAllHolonIDs(ctx)
	if err != nil {
		return err
	}

	calc := assurance.New(t.DB.GetRawDB())
	updatedCount := 0

	for _, id := range ids {
		_, err := calc.CalculateReliability(ctx, id)
		if err != nil {
			logger.Error().Err(err).Str("holon_id", id).Msg("error calculating R")
			continue
		}
		updatedCount++
	}

	logger.Info().Int("processed_count", updatedCount).Msg("decay update complete")
	return nil
}

func (t *Tools) Actualize() (string, error) {
	var report strings.Builder
	fpfDir := filepath.Join(t.RootDir, ".fpf")
	quintDir := t.GetFPFDir()

	if _, err := os.Stat(fpfDir); err == nil {
		report.WriteString("MIGRATION: Found legacy .fpf directory.\n")

		if _, err := os.Stat(quintDir); err == nil {
			return report.String(), fmt.Errorf("migration conflict: both .fpf and .quint exist. Please resolve manually")
		}

		report.WriteString("MIGRATION: Renaming .fpf -> .quint\n")
		if err := os.Rename(fpfDir, quintDir); err != nil {
			return report.String(), fmt.Errorf("failed to rename .fpf: %w", err)
		}
		report.WriteString("MIGRATION: Success.\n")
	}

	legacyDB := filepath.Join(quintDir, "fpf.db")
	newDB := filepath.Join(quintDir, "quint.db")

	if _, err := os.Stat(legacyDB); err == nil {
		report.WriteString("MIGRATION: Found legacy fpf.db.\n")
		if err := os.Rename(legacyDB, newDB); err != nil {
			return report.String(), fmt.Errorf("failed to rename fpf.db: %w", err)
		}
		report.WriteString("MIGRATION: Renamed to quint.db.\n")
	}

	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = t.RootDir
	output, err := cmd.Output()
	if err == nil {
		currentCommit := strings.TrimSpace(string(output))
		lastCommit := t.FSM.State.LastCommit

		if lastCommit == "" {
			report.WriteString(fmt.Sprintf("RECONCILIATION: Initializing baseline commit to %s\n", currentCommit))
			t.FSM.State.LastCommit = currentCommit
			if err := t.FSM.SaveState("default"); err != nil {
				report.WriteString(fmt.Sprintf("Warning: Failed to save state: %v\n", err))
			}
		} else if currentCommit != lastCommit {
			report.WriteString(fmt.Sprintf("RECONCILIATION: Detected changes since %s\n", lastCommit))
			diffCmd := exec.Command("git", "diff", "--name-status", lastCommit, "HEAD")
			diffCmd.Dir = t.RootDir
			diffOutput, err := diffCmd.Output()
			if err == nil {
				report.WriteString("Changed files:\n")
				report.WriteString(string(diffOutput))
			} else {
				report.WriteString(fmt.Sprintf("Warning: Failed to get diff: %v\n", err))
			}

			t.FSM.State.LastCommit = currentCommit
			if err := t.FSM.SaveState("default"); err != nil {
				report.WriteString(fmt.Sprintf("Warning: Failed to save state: %v\n", err))
			}
		} else {
			report.WriteString("RECONCILIATION: No changes detected (Clean).\n")
		}
	} else {
		report.WriteString("RECONCILIATION: Not a git repository or git error.\n")
	}

	return report.String(), nil
}

func (t *Tools) ResetCycle(ctx context.Context, reason, contextID string, abandonAll bool) (string, error) {
	defer t.RecordWork("ResetCycle", time.Now())

	logger.Info().
		Str("reason", reason).
		Str("context_id", contextID).
		Bool("abandon_all", abandonAll).
		Msg("ResetCycle called")

	if reason == "" {
		reason = "user requested reset"
	}
	var sb strings.Builder

	if contextID != "" {
		if t.DB == nil {
			return "", ErrDatabaseNotInitialized
		}
		if err := t.DB.AbandonContext(ctx, contextID); err != nil {
			return "", fmt.Errorf("failed to abandon context %s: %w", contextID, err)
		}
		t.AuditLog("quint_reset", "abandon_context", "agent", contextID, "SUCCESS",
			map[string]string{"reason": reason}, "")
		sb.WriteString(fmt.Sprintf("Abandoned context: %s\n", contextID))
		sb.WriteString(fmt.Sprintf("Reason: %s\n", reason))
		return sb.String(), nil
	}

	if abandonAll {
		if t.DB == nil {
			return "", ErrDatabaseNotInitialized
		}
		contexts, err := t.GetActiveDecisionContexts(ctx)
		if err != nil {
			return "", fmt.Errorf("failed to get active contexts: %w", err)
		}
		if len(contexts) == 0 {
			return "No active contexts to abandon.\n", nil
		}
		var abandoned []string
		for _, c := range contexts {
			if err := t.DB.AbandonContext(ctx, c.ID); err != nil {
				logger.Warn().Err(err).Str("context_id", c.ID).Msg("failed to abandon context")
				continue
			}
			abandoned = append(abandoned, c.ID)
		}
		t.AuditLog("quint_reset", "abandon_all_contexts", "agent", "", "SUCCESS",
			map[string]string{"reason": reason, "count": fmt.Sprintf("%d", len(abandoned))}, "")
		sb.WriteString(fmt.Sprintf("Abandoned %d contexts:\n", len(abandoned)))
		for _, id := range abandoned {
			sb.WriteString(fmt.Sprintf("  - %s\n", id))
		}
		sb.WriteString(fmt.Sprintf("Reason: %s\n", reason))
		return sb.String(), nil
	}

	currentStage := StageEmpty
	if activeContexts, err := t.GetActiveDecisionContexts(ctx); err == nil && len(activeContexts) > 0 {
		currentStage = t.getMostAdvancedStage(activeContexts)
	}

	sb.WriteString(fmt.Sprintf("Stage at reset: %s\n", currentStage))
	sb.WriteString(fmt.Sprintf("L0: %d, L1: %d, L2: %d, DRR: %d\n",
		t.countHolons(ctx, "L0"), t.countHolons(ctx, "L1"), t.countHolons(ctx, "L2"), t.countDRRs()))

	if t.DB != nil {
		openDecisions, err := t.GetOpenDecisions(ctx)
		if err == nil && len(openDecisions) > 0 {
			sb.WriteString(fmt.Sprintf("Open decisions: %d\n", len(openDecisions)))
			for _, d := range openDecisions {
				sb.WriteString(fmt.Sprintf("  - %s\n", d.ID))
			}
		}
	}

	t.AuditLog("quint_reset", "cycle_reset", "agent", "", "SUCCESS",
		map[string]string{"reason": reason, "from_stage": string(currentStage)},
		sb.String())

	return fmt.Sprintf("Cycle reset. Session ended.\nPrevious stage: %s\nReason: %s\n\n%s",
		currentStage, reason, sb.String()), nil
}

func (t *Tools) Compact(ctx context.Context, mode string, retentionDays int64) (string, error) {
	defer t.RecordWork("Compact", time.Now())

	if t.DB == nil {
		return "", fmt.Errorf("database not available")
	}

	if mode == "" {
		mode = "preview"
	}
	if retentionDays <= 0 {
		retentionDays = DefaultRetentionDays
	}
	result := CompactResult{
		Mode:          mode,
		RetentionDays: retentionDays,
	}

	count, err := t.DB.CountCompactableHolons(ctx, retentionDays)
	if err != nil {
		return "", fmt.Errorf("failed to count compactable holons: %w", err)
	}
	result.EligibleCount = count

	if count == 0 {
		return fmt.Sprintf("No holons eligible for compaction (retention: %d days).\n\nAll archived holons are either:\n- Less than %d days old, or\n- Already compacted", retentionDays, retentionDays), nil
	}

	holons, err := t.DB.GetArchivedHolonsForCompaction(ctx, retentionDays)
	if err != nil {
		return "", fmt.Errorf("failed to get compactable holons: %w", err)
	}

	var sb strings.Builder

	if mode == "preview" {
		sb.WriteString(fmt.Sprintf("## Compaction Preview (retention: %d days)\n\n", retentionDays))
		sb.WriteString(fmt.Sprintf("**%d holons eligible for compaction:**\n\n", count))
		sb.WriteString("| ID | Title | Layer | Decision | Outcome | Resolved |\n")
		sb.WriteString("|-----|-------|-------|----------|---------|----------|\n")

		for _, h := range holons {
			resolvedAt := "unknown"
			if h.ResolvedAt != nil {
				if t, ok := h.ResolvedAt.(time.Time); ok {
					resolvedAt = t.Format("2006-01-02")
				} else if s, ok := h.ResolvedAt.(string); ok && len(s) >= 10 {
					resolvedAt = s[:10]
				}
			}
			outcome := h.DecisionOutcome
			if outcome == "selects" {
				outcome = "SELECTED"
			} else if outcome == "rejects" {
				outcome = "REJECTED"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
				truncateString(h.ID, 12),
				truncateString(h.Title, 30),
				h.Layer,
				truncateString(h.DecisionTitle, 20),
				outcome,
				resolvedAt))
		}

		sb.WriteString("\n**Compaction removes:**\n")
		sb.WriteString("- Evidence records\n")
		sb.WriteString("- Characteristics\n")
		sb.WriteString("- Waivers\n")
		sb.WriteString("- Detailed content (replaced with '[COMPACTED]')\n")
		sb.WriteString("\n**Preserved:**\n")
		sb.WriteString("- Holon ID, title, type, kind, layer\n")
		sb.WriteString("- Relations (decision links)\n")
		sb.WriteString("- Audit log entries\n")
		sb.WriteString("\nTo execute: `quint_compact(mode=\"execute\", retention_days=")
		sb.WriteString(fmt.Sprintf("%d)`\n", retentionDays))

	} else if mode == "execute" {
		sb.WriteString(fmt.Sprintf("## Compaction Executed (retention: %d days)\n\n", retentionDays))

		for _, h := range holons {
			err := t.DB.CompactHolon(ctx, h.ID)
			if err != nil {
				result.Errors = append(result.Errors, fmt.Sprintf("%s: %v", h.ID, err))
				continue
			}
			result.CompactedHolons = append(result.CompactedHolons, h.ID)
			result.CompactedCount++
		}

		sb.WriteString(fmt.Sprintf("**Compacted %d holons**\n\n", result.CompactedCount))

		if len(result.Errors) > 0 {
			sb.WriteString("**Errors:**\n")
			for _, e := range result.Errors {
				sb.WriteString(fmt.Sprintf("- %s\n", e))
			}
			sb.WriteString("\n")
		}

		t.AuditLog("quint_compact", "compaction",
			string(RoleMaintainer), "",
			"SUCCESS",
			map[string]any{
				"retention_days": retentionDays,
				"compacted":      result.CompactedCount,
				"errors":         len(result.Errors),
			},
			fmt.Sprintf("Compacted %d holons", result.CompactedCount))

		sb.WriteString("Compaction complete. Holon metadata and decision links preserved.\n")

	} else {
		return "", fmt.Errorf("invalid mode: %s (use 'preview' or 'execute')", mode)
	}

	return sb.String(), nil
}

func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	if maxLen <= 3 {
		return s[:maxLen]
	}
	return s[:maxLen-3] + "..."
}
