package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/m0n0x41d/haft/internal/artifact"
	"github.com/m0n0x41d/haft/internal/graph"
)

// executionPlan is the structured plan generated by the planning agent.
// Persisted as .haft/plans/{decision-ref}.md
type executionPlan struct {
	decisionRef string
	title       string
	tasks       []planTask
	planFile    string // path to the markdown plan file
}

type planTask struct {
	id          string // T1, T2, ...
	title       string
	description string
	files       []string // files this task should touch
	acceptance  string   // how to verify this task is done
	status      string   // pending, running, passed, failed
}

// planFilePath returns where to persist the plan.
func planFilePath(haftDir, decisionRef string) string {
	return filepath.Join(haftDir, "plans", decisionRef+".md")
}

// generatePlan spawns a planning agent to decompose a decision into tasks.
func generatePlan(
	decision *artifact.Artifact,
	files []artifact.AffectedFile,
	invariants []string,
	projectRoot string,
	agent string,
	tc toolchain,
	contextFiles []string,
	extraPrompt string,
	ev *EventSender,
) (*executionPlan, error) {
	haftDir := filepath.Join(projectRoot, ".haft")
	_ = os.MkdirAll(filepath.Join(haftDir, "plans"), 0o755)

	planPath := planFilePath(haftDir, decision.Meta.ID)

	// Build planning prompt
	prompt := buildPlanningPrompt(decision, files, invariants, planPath, tc, projectRoot, contextFiles, extraPrompt)

	ev.Phase("Planning: Decomposing decision into tasks")
	ev.Meta("Plan path", planPath)

	// Run planning agent
	if err := spawnAgentWithEvents(agent, prompt, projectRoot, ev); err != nil {
		return nil, fmt.Errorf("planning agent failed: %w", err)
	}

	// Read generated plan
	plan, err := parsePlanFile(planPath, decision.Meta.ID, decision.Meta.Title)
	if err != nil {
		return nil, fmt.Errorf("failed to parse generated plan: %w", err)
	}

	ev.OK(fmt.Sprintf("Plan generated: %d tasks", len(plan.tasks)))
	emitPlanLoaded(ev, plan)

	return plan, nil
}

func buildPlanningPrompt(
	decision *artifact.Artifact,
	files []artifact.AffectedFile,
	invariants []string,
	outputPath string,
	tc toolchain,
	projectRoot string,
	contextFiles []string,
	extraPrompt string,
) string {
	var b strings.Builder

	_, _ = b.WriteString("# Task: Create Implementation Plan\n\n")
	_, _ = b.WriteString("Read the decision below and decompose it into a sequence of implementation tasks.\n\n")
	_, _ = b.WriteString("## Rules for the plan\n\n")
	_, _ = b.WriteString("1. Each task must be small enough for one focused agent session\n")
	_, _ = b.WriteString("2. Tasks must be ordered so each builds on previous (dependencies respected)\n")
	_, _ = b.WriteString("3. Each task must have clear acceptance criteria\n")
	_, _ = b.WriteString("4. Each task must list which files it will touch\n")
	_, _ = b.WriteString("5. Include a verification/test task after implementation tasks\n")
	_, _ = b.WriteString("6. Include a final review task that checks all invariants\n\n")

	_, _ = b.WriteString(fmt.Sprintf("## Output\n\nWrite the plan to: `%s`\n\n", outputPath))
	_, _ = b.WriteString("Use this exact format:\n\n")
	_, _ = b.WriteString("```markdown\n")
	_, _ = b.WriteString("# Implementation Plan: {decision title}\n\n")
	_, _ = b.WriteString("Decision: {decision-ref}\n\n")
	_, _ = b.WriteString("## Tasks\n\n")
	_, _ = b.WriteString("| # | Task | Files | Acceptance |\n")
	_, _ = b.WriteString("|---|------|-------|------------|\n")
	_, _ = b.WriteString("| T1 | First thing to do | `path/to/file.go` | How to verify it's done |\n")
	_, _ = b.WriteString("| T2 | Second thing | `path/a.go`, `path/b.go` | Acceptance criteria |\n")
	_, _ = b.WriteString(fmt.Sprintf("| TV | Run tests and verify | all modified files | %s |\n", tc.acceptLine()))
	_, _ = b.WriteString("| TR | Final review — check all invariants | — | All invariants hold, no regressions |\n")
	_, _ = b.WriteString("```\n\n")

	_, _ = b.WriteString("## Decision to decompose\n\n")
	_, _ = b.WriteString(fmt.Sprintf("### %s\n\n", decision.Meta.Title))
	_, _ = b.WriteString(fmt.Sprintf("ID: %s\n\n", decision.Meta.ID))
	_, _ = b.WriteString(decision.Body)
	_, _ = b.WriteString("\n\n")

	if len(files) > 0 {
		_, _ = b.WriteString("### Affected Files\n\n")
		for _, f := range files {
			_, _ = b.WriteString(fmt.Sprintf("- %s\n", f.Path))
		}
		_, _ = b.WriteString("\n")
	}

	if len(invariants) > 0 {
		_, _ = b.WriteString("### Invariants (must hold after implementation)\n\n")
		for _, inv := range invariants {
			_, _ = b.WriteString(fmt.Sprintf("- %s\n", inv))
		}
		_, _ = b.WriteString("\n")
	}

	appendContextAndPrompt(&b, projectRoot, contextFiles, extraPrompt)

	_, _ = b.WriteString("Now create the plan and write it to the output file.\n")

	return b.String()
}

// parsePlanFile reads the generated markdown plan and extracts tasks.
func parsePlanFile(path, decisionRef, decisionTitle string) (*executionPlan, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read plan file: %w", err)
	}

	plan := &executionPlan{
		decisionRef: decisionRef,
		title:       decisionTitle,
		planFile:    path,
	}

	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "|") {
			continue
		}
		cols := strings.Split(line, "|")
		if len(cols) < 5 {
			continue
		}

		id := strings.TrimSpace(cols[1])
		if id == "#" || id == "" || strings.HasPrefix(id, "-") {
			continue
		}

		title := strings.TrimSpace(cols[2])
		files := strings.TrimSpace(cols[3])
		accept := strings.TrimSpace(cols[4])

		// Parse file list
		var fileList []string
		for _, f := range strings.Split(files, ",") {
			f = strings.TrimSpace(f)
			f = strings.Trim(f, "`")
			if f != "" && f != "—" && f != "-" {
				fileList = append(fileList, f)
			}
		}

		plan.tasks = append(plan.tasks, planTask{
			id:         id,
			title:      title,
			files:      fileList,
			acceptance: accept,
			status:     "pending",
		})
	}

	if len(plan.tasks) == 0 {
		return nil, fmt.Errorf("no tasks found in plan file %s", path)
	}

	return plan, nil
}

// executePlan runs all tasks in the plan with verification between each.
func executePlan(
	ctx context.Context,
	plan *executionPlan,
	decision *artifact.Artifact,
	artStore *artifact.Store,
	graphStore *graph.Store,
	projectRoot string,
	agent string,
	auto bool,
	tc toolchain,
	contextFiles []string,
	extraPrompt string,
	ev *EventSender,
) bool {
	allPassed := true

	for i := range plan.tasks {
		task := &plan.tasks[i]

		ev.Phase(fmt.Sprintf("Task %s/%d: %s", task.id, len(plan.tasks), task.title))
		if task.acceptance != "" {
			ev.Meta("Accept", task.acceptance)
		}
		if len(task.files) > 0 {
			ev.Meta("Files", strings.Join(task.files, ", "))
		}

		if !auto {
			fmt.Printf("\n  %sRun this task? [Y/n/s(kip)] %s", aBold, aReset)
			var answer string
			fmt.Scanln(&answer)
			if answer == "n" || answer == "N" {
				return false
			}
			if answer == "s" || answer == "S" {
				task.status = "skipped"
				ev.TaskStatus(task.id, task.title, TaskSkipped, 0, "")
				continue
			}
		}

		// Build task prompt
		prompt := buildTaskPrompt(decision, task, tc, projectRoot, contextFiles, extraPrompt)
		task.status = "running"
		ev.TaskStatus(task.id, task.title, TaskRunning, 0, "")

		// Execute
		start := time.Now()
		if err := spawnAgentWithEvents(agent, prompt, projectRoot, ev); err != nil {
			elapsed := time.Since(start)
			task.status = "failed"
			ev.TaskStatus(task.id, task.title, TaskFailed, elapsed, err.Error())
			allPassed = false
			if !auto {
				fmt.Printf("  %sContinue? [Y/n] %s", aBold, aReset)
				var answer string
				fmt.Scanln(&answer)
				if answer == "n" || answer == "N" {
					return false
				}
			}
			continue
		}

		elapsed := time.Since(start)
		ev.TaskStatus(task.id, task.title, TaskPassed, elapsed, "")

		// Mid-task verification: check build
		ev.Phase(fmt.Sprintf("Verify after %s", task.id))
		buildOk := runBuildCheck(tc, projectRoot, ev)
		if !buildOk {
			task.status = "failed"
			allPassed = false
			ev.Fail("Build failed — spawning fix agent")

			fixPrompt := fmt.Sprintf(
				"The build is broken after implementing task %s (%s). Fix the compilation errors.\n%s\n",
				task.id, task.title, tc.verifyHint,
			)
			_ = spawnAgentWithEvents(agent, fixPrompt, projectRoot, ev)

			if !runBuildCheck(tc, projectRoot, ev) {
				ev.Fail("Build still broken after fix attempt")
				if !auto {
					fmt.Printf("  %sContinue? [Y/n] %s", aBold, aReset)
					var answer string
					fmt.Scanln(&answer)
					if answer == "n" || answer == "N" {
						return false
					}
				}
				continue
			}
		}

		task.status = "passed"
	}

	return allPassed
}

func buildTaskPrompt(decision *artifact.Artifact, task *planTask, tc toolchain, projectRoot string, contextFiles []string, extraPrompt string) string {
	var b strings.Builder

	_, _ = b.WriteString(fmt.Sprintf("# Implement: %s\n\n", task.title))
	_, _ = b.WriteString(fmt.Sprintf("This is task %s from the implementation plan for decision: %s\n\n", task.id, decision.Meta.Title))

	_, _ = b.WriteString("## What to do\n\n")
	_, _ = b.WriteString(task.title)
	_, _ = b.WriteString("\n\n")

	if len(task.files) > 0 {
		_, _ = b.WriteString("## Files to modify\n\n")
		for _, f := range task.files {
			_, _ = b.WriteString(fmt.Sprintf("- %s\n", f))
		}
		_, _ = b.WriteString("\nStay within these files. Do not modify unrelated code.\n\n")
	}

	if task.acceptance != "" {
		_, _ = b.WriteString("## Acceptance\n\n")
		_, _ = b.WriteString(task.acceptance)
		_, _ = b.WriteString("\n\n")
	}

	_, _ = b.WriteString("## Decision Context\n\n")
	_, _ = b.WriteString(decision.Body)
	_, _ = b.WriteString("\n\n")

	appendContextAndPrompt(&b, projectRoot, contextFiles, extraPrompt)

	_, _ = b.WriteString("## Rules\n\n")
	_, _ = b.WriteString("1. Read existing code before editing.\n")
	_, _ = b.WriteString("2. Make minimal, focused changes for this task only.\n")
	_, _ = b.WriteString(fmt.Sprintf("3. %s\n", tc.verifyHint))
	_, _ = b.WriteString("4. Do NOT commit — the runner manages commits.\n")

	return b.String()
}

// appendContextAndPrompt appends extra context files and prompt to a prompt builder.
func appendContextAndPrompt(b *strings.Builder, projectRoot string, contextFiles []string, extraPrompt string) {
	for _, cf := range contextFiles {
		absPath := cf
		if !filepath.IsAbs(cf) {
			absPath = filepath.Join(projectRoot, cf)
		}
		data, err := os.ReadFile(absPath)
		if err != nil {
			_, _ = b.WriteString(fmt.Sprintf("## Context: %s\n\n(file not found: %v)\n\n", cf, err))
			continue
		}
		_, _ = b.WriteString(fmt.Sprintf("## Context: %s\n\n", cf))
		_, _ = b.Write(data)
		_, _ = b.WriteString("\n\n")
	}

	if extraPrompt != "" {
		_, _ = b.WriteString("## Additional Instructions\n\n")
		_, _ = b.WriteString(extraPrompt)
		_, _ = b.WriteString("\n\n")
	}
}

func runBuildCheck(tc toolchain, projectRoot string, ev *EventSender) bool {
	if tc.buildCmd == "" {
		return true
	}
	cmd := newShellCmd(tc.buildCmd, projectRoot)
	if err := cmd.Run(); err != nil {
		ev.Build(tc.buildCmd, false, "")
		return false
	}
	ev.Build(tc.buildCmd, true, "")
	return true
}

// finalReview runs full invariant verification + drift check + test suite.
func finalReview(
	ctx context.Context,
	decisionRef string,
	graphStore *graph.Store,
	artStore *artifact.Store,
	projectRoot string,
	agent string,
	auto bool,
	tc toolchain,
	ev *EventSender,
) bool {
	ev.Phase("Final Review")

	allGood := true

	// 1. Invariant verification
	ev.Phase("Invariants")
	results, err := graph.VerifyInvariants(ctx, graphStore, nil, decisionRef)
	if err != nil {
		ev.Warn(fmt.Sprintf("Invariant check error: %v", err))
	} else {
		for _, r := range results {
			switch r.Status {
			case graph.InvariantHolds:
				ev.Invariant(r.Invariant.DecisionID, r.Invariant.Text, true, "")
			case graph.InvariantViolated:
				allGood = false
				ev.Invariant(r.Invariant.DecisionID, r.Invariant.Text, false, r.Reason)
			default:
				ev.Warn(fmt.Sprintf("[%s] %s — status unknown", r.Invariant.DecisionID, r.Invariant.Text))
			}
		}
	}

	// 2. Build check
	ev.Phase("Build")
	if !runBuildCheck(tc, projectRoot, ev) {
		allGood = false
	}

	// 3. Test suite
	ev.Phase("Tests")
	if tc.testCmd != "" {
		testCmd := newShellCmd(tc.testCmd, projectRoot)
		if err := testCmd.Run(); err != nil {
			ev.Fail("Tests failed")
			allGood = false
		} else {
			ev.OK("Tests passed")
		}
	} else {
		ev.Warn("No test command detected — skipping")
	}

	// 4. If failures, offer fix
	if !allGood {
		ev.Fail("Review found issues")

		spawnFix := auto
		if !auto {
			fmt.Printf("\n  %sSpawn fix agent? [Y/n] %s", aBold, aReset)
			var answer string
			fmt.Scanln(&answer)
			spawnFix = answer != "n" && answer != "N"
		}

		if spawnFix {
			var fixPrompt strings.Builder
			_, _ = fixPrompt.WriteString("# Fix Review Issues\n\n")
			_, _ = fixPrompt.WriteString("The following issues were found during final review:\n\n")

			if err == nil {
				for _, r := range results {
					if r.Status == graph.InvariantViolated {
						_, _ = fixPrompt.WriteString(fmt.Sprintf("- INVARIANT VIOLATED: %s — %s\n", r.Invariant.Text, r.Reason))
					}
				}
			}
			_, _ = fixPrompt.WriteString(fmt.Sprintf("\nFix all issues. %s\n", tc.verifyHint))

			ev.Phase("Fix Agent")
			_ = spawnAgentWithEvents(agent, fixPrompt.String(), projectRoot, ev)

			// Re-check
			return finalReview(ctx, decisionRef, graphStore, artStore, projectRoot, agent, auto, tc, ev)
		}
	}

	return allGood
}
