package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/m0n0x41d/haft/internal/artifact"
	"github.com/m0n0x41d/haft/internal/graph"
)

// executionPlan is the structured plan generated by the planning agent.
// Persisted as .haft/plans/{decision-ref}.md
type executionPlan struct {
	decisionRef string
	title       string
	tasks       []planTask
	planFile    string // path to the markdown plan file
}

type planTask struct {
	id          string // T1, T2, ...
	title       string
	description string
	files       []string // files this task should touch
	acceptance  string   // how to verify this task is done
	status      string   // pending, running, passed, failed
}

// planFilePath returns where to persist the plan.
func planFilePath(haftDir, decisionRef string) string {
	return filepath.Join(haftDir, "plans", decisionRef+".md")
}

// generatePlan spawns a planning agent to decompose a decision into tasks.
func generatePlan(
	decision *artifact.Artifact,
	files []artifact.AffectedFile,
	invariants []string,
	projectRoot string,
	agent string,
	ui *runUI,
) (*executionPlan, error) {
	haftDir := filepath.Join(projectRoot, ".haft")
	_ = os.MkdirAll(filepath.Join(haftDir, "plans"), 0o755)

	planPath := planFilePath(haftDir, decision.Meta.ID)

	// Build planning prompt
	prompt := buildPlanningPrompt(decision, files, invariants, planPath)

	ui.phase("Planning: Decomposing decision into tasks")
	fmt.Printf("  %sAgent will analyze the decision and create a task plan%s\n", aDim, aReset)
	fmt.Printf("  %sPlan will be saved to: %s%s\n\n", aDim, planPath, aReset)

	// Run planning agent
	if err := spawnAgent(agent, prompt, projectRoot); err != nil {
		return nil, fmt.Errorf("planning agent failed: %w", err)
	}

	// Read generated plan
	plan, err := parsePlanFile(planPath, decision.Meta.ID, decision.Meta.Title)
	if err != nil {
		return nil, fmt.Errorf("failed to parse generated plan: %w", err)
	}

	ui.ok(fmt.Sprintf("Plan generated: %d tasks", len(plan.tasks)))
	for _, t := range plan.tasks {
		fmt.Printf("  %s%-4s%s %s\n", aCyan, t.id, aReset, t.title)
		if t.acceptance != "" {
			fmt.Printf("       %s✓ %s%s\n", aDim, t.acceptance, aReset)
		}
	}
	fmt.Println()

	return plan, nil
}

func buildPlanningPrompt(
	decision *artifact.Artifact,
	files []artifact.AffectedFile,
	invariants []string,
	outputPath string,
) string {
	var b strings.Builder

	_, _ = b.WriteString("# Task: Create Implementation Plan\n\n")
	_, _ = b.WriteString("Read the decision below and decompose it into a sequence of implementation tasks.\n\n")
	_, _ = b.WriteString("## Rules for the plan\n\n")
	_, _ = b.WriteString("1. Each task must be small enough for one focused agent session\n")
	_, _ = b.WriteString("2. Tasks must be ordered so each builds on previous (dependencies respected)\n")
	_, _ = b.WriteString("3. Each task must have clear acceptance criteria\n")
	_, _ = b.WriteString("4. Each task must list which files it will touch\n")
	_, _ = b.WriteString("5. Include a verification/test task after implementation tasks\n")
	_, _ = b.WriteString("6. Include a final review task that checks all invariants\n\n")

	_, _ = b.WriteString(fmt.Sprintf("## Output\n\nWrite the plan to: `%s`\n\n", outputPath))
	_, _ = b.WriteString("Use this exact format:\n\n")
	_, _ = b.WriteString("```markdown\n")
	_, _ = b.WriteString("# Implementation Plan: {decision title}\n\n")
	_, _ = b.WriteString("Decision: {decision-ref}\n\n")
	_, _ = b.WriteString("## Tasks\n\n")
	_, _ = b.WriteString("| # | Task | Files | Acceptance |\n")
	_, _ = b.WriteString("|---|------|-------|------------|\n")
	_, _ = b.WriteString("| T1 | First thing to do | `path/to/file.go` | How to verify it's done |\n")
	_, _ = b.WriteString("| T2 | Second thing | `path/a.go`, `path/b.go` | Acceptance criteria |\n")
	_, _ = b.WriteString("| TV | Run tests and verify | all modified files | All tests pass, go build succeeds |\n")
	_, _ = b.WriteString("| TR | Final review — check all invariants | — | All invariants hold, no regressions |\n")
	_, _ = b.WriteString("```\n\n")

	_, _ = b.WriteString("## Decision to decompose\n\n")
	_, _ = b.WriteString(fmt.Sprintf("### %s\n\n", decision.Meta.Title))
	_, _ = b.WriteString(fmt.Sprintf("ID: %s\n\n", decision.Meta.ID))
	_, _ = b.WriteString(decision.Body)
	_, _ = b.WriteString("\n\n")

	if len(files) > 0 {
		_, _ = b.WriteString("### Affected Files\n\n")
		for _, f := range files {
			_, _ = b.WriteString(fmt.Sprintf("- %s\n", f.Path))
		}
		_, _ = b.WriteString("\n")
	}

	if len(invariants) > 0 {
		_, _ = b.WriteString("### Invariants (must hold after implementation)\n\n")
		for _, inv := range invariants {
			_, _ = b.WriteString(fmt.Sprintf("- %s\n", inv))
		}
		_, _ = b.WriteString("\n")
	}

	_, _ = b.WriteString("Now create the plan and write it to the output file.\n")

	return b.String()
}

// parsePlanFile reads the generated markdown plan and extracts tasks.
func parsePlanFile(path, decisionRef, decisionTitle string) (*executionPlan, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read plan file: %w", err)
	}

	plan := &executionPlan{
		decisionRef: decisionRef,
		title:       decisionTitle,
		planFile:    path,
	}

	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "|") {
			continue
		}
		cols := strings.Split(line, "|")
		if len(cols) < 5 {
			continue
		}

		id := strings.TrimSpace(cols[1])
		if id == "#" || id == "" || strings.HasPrefix(id, "-") {
			continue
		}

		title := strings.TrimSpace(cols[2])
		files := strings.TrimSpace(cols[3])
		accept := strings.TrimSpace(cols[4])

		// Parse file list
		var fileList []string
		for _, f := range strings.Split(files, ",") {
			f = strings.TrimSpace(f)
			f = strings.Trim(f, "`")
			if f != "" && f != "—" && f != "-" {
				fileList = append(fileList, f)
			}
		}

		plan.tasks = append(plan.tasks, planTask{
			id:         id,
			title:      title,
			files:      fileList,
			acceptance: accept,
			status:     "pending",
		})
	}

	if len(plan.tasks) == 0 {
		return nil, fmt.Errorf("no tasks found in plan file %s", path)
	}

	return plan, nil
}

// executePlan runs all tasks in the plan with verification between each.
func executePlan(
	ctx context.Context,
	plan *executionPlan,
	decision *artifact.Artifact,
	artStore *artifact.Store,
	graphStore *graph.Store,
	projectRoot string,
	agent string,
	auto bool,
	ui *runUI,
) bool {
	allPassed := true

	for i := range plan.tasks {
		task := &plan.tasks[i]

		ui.phase(fmt.Sprintf("Task %s/%d: %s", task.id, len(plan.tasks), task.title))
		if task.acceptance != "" {
			fmt.Printf("  %sAccept: %s%s\n", aDim, task.acceptance, aReset)
		}
		if len(task.files) > 0 {
			fmt.Printf("  %sFiles: %s%s\n", aDim, strings.Join(task.files, ", "), aReset)
		}
		fmt.Println()

		if !auto {
			fmt.Printf("  %sRun this task? [Y/n/s(kip)] %s", aBold, aReset)
			var answer string
			fmt.Scanln(&answer)
			if answer == "n" || answer == "N" {
				return false
			}
			if answer == "s" || answer == "S" {
				task.status = "skipped"
				continue
			}
		}

		// Build task prompt
		prompt := buildTaskPrompt(decision, task)
		task.status = "running"

		// Execute
		start := time.Now()
		if err := spawnAgent(agent, prompt, projectRoot); err != nil {
			task.status = "failed"
			ui.fail(fmt.Sprintf("Task %s failed: %v", task.id, err))
			allPassed = false
			if !auto {
				fmt.Printf("  %sContinue? [Y/n] %s", aBold, aReset)
				var answer string
				fmt.Scanln(&answer)
				if answer == "n" || answer == "N" {
					return false
				}
			}
			continue
		}

		elapsed := time.Since(start)
		ui.ok(fmt.Sprintf("Task %s done (%ds)", task.id, int(elapsed.Seconds())))

		// Mid-task verification: run tests, check build
		ui.phase(fmt.Sprintf("Verify after %s", task.id))
		buildOk := runBuildCheck(projectRoot, ui)
		if !buildOk {
			task.status = "failed"
			allPassed = false
			ui.fail("Build failed — spawning fix agent")

			fixPrompt := fmt.Sprintf(
				"The build is broken after implementing task %s (%s). Fix the compilation errors.\nRun `go build ./cmd/haft/` to verify.\n",
				task.id, task.title,
			)
			_ = spawnAgent(agent, fixPrompt, projectRoot)

			if !runBuildCheck(projectRoot, ui) {
				ui.fail("Build still broken after fix attempt")
				if !auto {
					fmt.Printf("  %sContinue? [Y/n] %s", aBold, aReset)
					var answer string
					fmt.Scanln(&answer)
					if answer == "n" || answer == "N" {
						return false
					}
				}
				continue
			}
		}

		task.status = "passed"
	}

	return allPassed
}

func buildTaskPrompt(decision *artifact.Artifact, task *planTask) string {
	var b strings.Builder

	_, _ = b.WriteString(fmt.Sprintf("# Implement: %s\n\n", task.title))
	_, _ = b.WriteString(fmt.Sprintf("This is task %s from the implementation plan for decision: %s\n\n", task.id, decision.Meta.Title))

	_, _ = b.WriteString("## What to do\n\n")
	_, _ = b.WriteString(task.title)
	_, _ = b.WriteString("\n\n")

	if len(task.files) > 0 {
		_, _ = b.WriteString("## Files to modify\n\n")
		for _, f := range task.files {
			_, _ = b.WriteString(fmt.Sprintf("- %s\n", f))
		}
		_, _ = b.WriteString("\nStay within these files. Do not modify unrelated code.\n\n")
	}

	if task.acceptance != "" {
		_, _ = b.WriteString("## Acceptance\n\n")
		_, _ = b.WriteString(task.acceptance)
		_, _ = b.WriteString("\n\n")
	}

	_, _ = b.WriteString("## Decision Context\n\n")
	_, _ = b.WriteString(decision.Body)
	_, _ = b.WriteString("\n\n")

	_, _ = b.WriteString("## Rules\n\n")
	_, _ = b.WriteString("1. Read existing code before editing.\n")
	_, _ = b.WriteString("2. Make minimal, focused changes for this task only.\n")
	_, _ = b.WriteString("3. Run `go build ./cmd/haft/` to verify compilation.\n")
	_, _ = b.WriteString("4. Do NOT commit — the runner manages commits.\n")

	return b.String()
}

func runBuildCheck(projectRoot string, ui *runUI) bool {
	// Try go build
	buildCmd := newShellCmd("go build -o /dev/null ./cmd/haft/", projectRoot)
	if err := buildCmd.Run(); err != nil {
		ui.fail("go build failed")
		return false
	}
	ui.ok("go build passed")
	return true
}

// finalReview runs full invariant verification + drift check + test suite.
func finalReview(
	ctx context.Context,
	decisionRef string,
	graphStore *graph.Store,
	artStore *artifact.Store,
	projectRoot string,
	agent string,
	ui *runUI,
) bool {
	ui.phase("Final Review")

	allGood := true

	// 1. Invariant verification
	fmt.Printf("  %s── Invariants ──%s\n", aDim, aReset)
	results, err := graph.VerifyInvariants(ctx, graphStore, nil, decisionRef)
	if err != nil {
		ui.warn(fmt.Sprintf("Invariant check error: %v", err))
	} else {
		for _, r := range results {
			switch r.Status {
			case graph.InvariantHolds:
				ui.invariantResult(r.Invariant.DecisionID, r.Invariant.Text, true)
			case graph.InvariantViolated:
				allGood = false
				ui.invariantResult(r.Invariant.DecisionID, r.Invariant.Text, false)
				fmt.Printf("       %s%s%s\n", aRed, r.Reason, aReset)
			default:
				fmt.Printf("  %s?%s %s%s%s\n", aYellow, aReset, aDim, r.Invariant.Text, aReset)
			}
		}
	}

	// 2. Build check
	fmt.Printf("\n  %s── Build ──%s\n", aDim, aReset)
	if !runBuildCheck(projectRoot, ui) {
		allGood = false
	}

	// 3. Test suite
	fmt.Printf("\n  %s── Tests ──%s\n", aDim, aReset)
	testCmd := newShellCmd("go test $(go list ./... | grep -v /desktop) 2>&1 | tail -5", projectRoot)
	if err := testCmd.Run(); err != nil {
		ui.fail("Tests failed")
		allGood = false
	} else {
		ui.ok("Tests passed")
	}

	// 4. If failures, offer fix
	if !allGood {
		fmt.Println()
		ui.fail("Review found issues")

		fmt.Printf("\n  %sSpawn fix agent? [Y/n] %s", aBold, aReset)
		var answer string
		fmt.Scanln(&answer)
		if answer != "n" && answer != "N" {
			var fixPrompt strings.Builder
			_, _ = fixPrompt.WriteString("# Fix Review Issues\n\n")
			_, _ = fixPrompt.WriteString("The following issues were found during final review:\n\n")

			if err == nil {
				for _, r := range results {
					if r.Status == graph.InvariantViolated {
						_, _ = fixPrompt.WriteString(fmt.Sprintf("- INVARIANT VIOLATED: %s — %s\n", r.Invariant.Text, r.Reason))
					}
				}
			}
			_, _ = fixPrompt.WriteString("\nFix all issues. Run `go build ./cmd/haft/` and `go test $(go list ./... | grep -v /desktop)` to verify.\n")

			ui.phase("Fix Agent")
			_ = spawnAgent(agent, fixPrompt.String(), projectRoot)

			// Re-check
			return finalReview(ctx, decisionRef, graphStore, artStore, projectRoot, agent, ui)
		}
	}

	return allGood
}
