package project

import "path/filepath"

const (
	projectConfigFile = "config.yaml"

	// legacyGeneratedAuthorityOnlyProjectConfigDigest identifies the one
	// project-local behavior carrier emitted by Haft before schema 56. The
	// carrier is obsolete: current authority policy has no project-local
	// switches. Keeping only its digest prevents init from reinterpreting or
	// normalizing operator-edited YAML while still allowing exact cleanup.
	legacyGeneratedAuthorityOnlyProjectConfigDigest = "sha256:026df268318667889d690421e63e3183ec25dafab012967fba4eb2e0c032a438"
)

// ProjectConfigPath returns the obsolete project-local behavior-config path.
// Current runtime code must not read this carrier; haft init uses the path only
// to remove the exact historical generated file or warn about preserved bytes.
func ProjectConfigPath(haftDir string) string {
	return filepath.Join(haftDir, projectConfigFile)
}

// IsKnownGeneratedLegacyProjectConfigDigest reports whether a digest belongs
// to the exact authority-only carrier previously generated by Haft. Unknown
// bytes are operator-owned and must be preserved byte-for-byte.
func IsKnownGeneratedLegacyProjectConfigDigest(digest string) bool {
	return digest == legacyGeneratedAuthorityOnlyProjectConfigDigest
}
