package fpfrefresh

import (
	"bytes"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"

	_ "modernc.org/sqlite"
)

func TestIntegrationLockCanonicalRoundTripAndHandEditRejection(t *testing.T) {
	t.Parallel()

	lock := testIntegrationLock()
	payload, err := MarshalIntegrationLock(lock)
	if err != nil {
		t.Fatalf("MarshalIntegrationLock() error: %v", err)
	}
	parsed, err := ParseIntegrationLock(payload)
	if err != nil {
		t.Fatalf("ParseIntegrationLock() error: %v", err)
	}
	if parsed.Coordinates != lock.Coordinates {
		t.Fatalf("parsed coordinates = %#v, want %#v", parsed.Coordinates, lock.Coordinates)
	}

	handEdited := bytes.Replace(payload, []byte("  \"generated_by\""), []byte("    \"generated_by\""), 1)
	if _, err := ParseIntegrationLock(handEdited); err == nil ||
		!strings.Contains(err.Error(), "not canonical generated bytes") {
		t.Fatalf("hand-edited lock error = %v, want canonical generation failure", err)
	}

	withUnknownField := bytes.Replace(
		payload,
		[]byte("{\n"),
		[]byte("{\n  \"approval\": true,\n"),
		1,
	)
	if _, err := ParseIntegrationLock(withUnknownField); err == nil ||
		!strings.Contains(err.Error(), "unknown field") {
		t.Fatalf("unknown-field lock error = %v, want closed schema failure", err)
	}
}

func TestBuildAndVerifyIntegrationLockBindsSourceDatabaseAndTypeEnv(t *testing.T) {
	t.Parallel()

	directory := t.TempDir()
	readmePath := filepath.Join(directory, "Readme.md")
	specPath := filepath.Join(directory, "FPF-Spec.md")
	databasePath := filepath.Join(directory, "fpf.db")
	if err := os.WriteFile(readmePath, []byte("readme bytes\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(specPath, []byte("spec bytes\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	readmeDigest, err := digestFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	specDigest, err := digestFile(specPath)
	if err != nil {
		t.Fatal(err)
	}

	const revision = "308edacfa2bdb2c60d07e4e10c0deb1f260a6a31"
	const typeEnvDigest = "sha256:95c7d74bb119410305557a42dca33aabf5f8701a0ce329280338bd8324ef6a13"
	createIntegrationMetaFixture(t, databasePath, map[string]string{
		"fpf_commit":                      revision,
		"indexed_source_units":            "16",
		"readme_document_digest":          readmeDigest,
		"schema_version":                  "11",
		"spec_document_digest":            specDigest,
		"typeenv_artifact_digest":         typeEnvDigest,
		"typeenv_compiler_schema_version": "fpf-base-typeenv.cov2.v5",
		"typeenv_ref":                     "typeenv:" + typeEnvDigest,
		"typeenv_source_revision":         revision,
	})
	input := IntegrationCoordinateInput{
		SourceRevision: revision,
		ReadmePath:     readmePath,
		SpecPath:       specPath,
		DatabasePath:   databasePath,
		GeneratedBy:    "fpf-refresh@test",
	}
	lock, err := BuildIntegrationLock(input)
	if err != nil {
		t.Fatalf("BuildIntegrationLock() error: %v", err)
	}
	if lock.Coordinates.SourceUnitCount != 16 ||
		lock.Coordinates.SourceRevision != revision ||
		lock.Coordinates.DatabaseDigest == "" {
		t.Fatalf("lock coordinates = %#v", lock.Coordinates)
	}
	if err := VerifyIntegrationLock(lock, input); err != nil {
		t.Fatalf("VerifyIntegrationLock() error: %v", err)
	}

	if err := os.WriteFile(specPath, []byte("changed spec bytes\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := VerifyIntegrationLock(lock, input); err == nil ||
		!strings.Contains(err.Error(), "snapshot_pin_stale") {
		t.Fatalf("stale spec verification error = %v, want snapshot_pin_stale", err)
	}
}

func TestWriteIntegrationLockUsesCanonicalBytes(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "nested", "fpf-integration.lock.json")
	lock := testIntegrationLock()
	if err := WriteIntegrationLock(path, lock); err != nil {
		t.Fatalf("WriteIntegrationLock() error: %v", err)
	}
	payload, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	canonical, err := MarshalIntegrationLock(lock)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(payload, canonical) {
		t.Fatalf("written lock differs from canonical bytes\nwritten=%s\nwant=%s", payload, canonical)
	}
}

func testIntegrationLock() IntegrationLock {
	const digest = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	return IntegrationLock{
		SchemaVersion: IntegrationLockSchemaVersion,
		GeneratedBy:   "fpf-refresh@test",
		Coordinates: IntegrationCoordinates{
			SourceRevision:         "308edacfa2bdb2c60d07e4e10c0deb1f260a6a31",
			ReadmeDocumentDigest:   digest,
			SpecDocumentDigest:     digest,
			DatabaseDigest:         digest,
			SourceUnitCount:        16,
			IndexSchemaVersion:     "11",
			BaseTypeEnvRef:         "typeenv:" + digest,
			BaseTypeEnvDigest:      digest,
			TypeEnvCompilerEdition: "fpf-base-typeenv.cov2.v5",
		},
		TokenGate: &TokenGateCoordinates{
			FixtureRevision: "fixture-v1",
			FixtureDigest:   digest,
		},
	}
}

func createIntegrationMetaFixture(t *testing.T, path string, values map[string]string) {
	t.Helper()
	database, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := database.Exec(`CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)`); err != nil {
		_ = database.Close()
		t.Fatal(err)
	}
	for key, value := range values {
		if _, err := database.Exec(`INSERT INTO meta(key, value) VALUES (?, ?)`, key, value); err != nil {
			_ = database.Close()
			t.Fatal(err)
		}
	}
	if err := database.Close(); err != nil {
		t.Fatal(err)
	}
}
