// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function Adopt(arg1) {
  return window['go']['main']['App']['Adopt'](arg1);
}

export function AdoptProblemCandidate(arg1) {
  return window['go']['main']['App']['AdoptProblemCandidate'](arg1);
}

export function ArchiveTask(arg1) {
  return window['go']['main']['App']['ArchiveTask'](arg1);
}

export function AssessComparisonReadiness(arg1) {
  return window['go']['main']['App']['AssessComparisonReadiness'](arg1);
}

export function BaselineDecision(arg1) {
  return window['go']['main']['App']['BaselineDecision'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CharacterizeProblem(arg1) {
  return window['go']['main']['App']['CharacterizeProblem'](arg1);
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function ComparePortfolio(arg1) {
  return window['go']['main']['App']['ComparePortfolio'](arg1);
}

export function CreateDecision(arg1) {
  return window['go']['main']['App']['CreateDecision'](arg1);
}

export function CreateFlow(arg1) {
  return window['go']['main']['App']['CreateFlow'](arg1);
}

export function CreatePortfolio(arg1) {
  return window['go']['main']['App']['CreatePortfolio'](arg1);
}

export function CreateProblem(arg1) {
  return window['go']['main']['App']['CreateProblem'](arg1);
}

export function CreatePullRequest(arg1) {
  return window['go']['main']['App']['CreatePullRequest'](arg1);
}

export function CreateTerminalSession(arg1) {
  return window['go']['main']['App']['CreateTerminalSession'](arg1);
}

export function DeleteFlow(arg1) {
  return window['go']['main']['App']['DeleteFlow'](arg1);
}

export function DeprecateDecision(arg1, arg2) {
  return window['go']['main']['App']['DeprecateDecision'](arg1, arg2);
}

export function DetectAgents() {
  return window['go']['main']['App']['DetectAgents']();
}

export function DismissProblemCandidate(arg1) {
  return window['go']['main']['App']['DismissProblemCandidate'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCoverage() {
  return window['go']['main']['App']['GetCoverage']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetDecision(arg1) {
  return window['go']['main']['App']['GetDecision'](arg1);
}

export function GetGovernanceOverview() {
  return window['go']['main']['App']['GetGovernanceOverview']();
}

export function GetPortfolio(arg1) {
  return window['go']['main']['App']['GetPortfolio'](arg1);
}

export function GetProblem(arg1) {
  return window['go']['main']['App']['GetProblem'](arg1);
}

export function GetTaskOutput(arg1) {
  return window['go']['main']['App']['GetTaskOutput'](arg1);
}

export function HandoffTask(arg1, arg2) {
  return window['go']['main']['App']['HandoffTask'](arg1, arg2);
}

export function Implement(arg1) {
  return window['go']['main']['App']['Implement'](arg1);
}

export function ImplementDecision(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImplementDecision'](arg1, arg2, arg3, arg4);
}

export function InitProject(arg1) {
  return window['go']['main']['App']['InitProject'](arg1);
}

export function ListAllTasks() {
  return window['go']['main']['App']['ListAllTasks']();
}

export function ListDecisions() {
  return window['go']['main']['App']['ListDecisions']();
}

export function ListFlowTemplates() {
  return window['go']['main']['App']['ListFlowTemplates']();
}

export function ListFlows() {
  return window['go']['main']['App']['ListFlows']();
}

export function ListPortfolios() {
  return window['go']['main']['App']['ListPortfolios']();
}

export function ListProblemCandidates() {
  return window['go']['main']['App']['ListProblemCandidates']();
}

export function ListProblems() {
  return window['go']['main']['App']['ListProblems']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListTerminalSessions() {
  return window['go']['main']['App']['ListTerminalSessions']();
}

export function MeasureDecision(arg1, arg2, arg3) {
  return window['go']['main']['App']['MeasureDecision'](arg1, arg2, arg3);
}

export function OpenDirectoryPicker() {
  return window['go']['main']['App']['OpenDirectoryPicker']();
}

export function OpenPathInIDE(arg1) {
  return window['go']['main']['App']['OpenPathInIDE'](arg1);
}

export function RefreshGovernance() {
  return window['go']['main']['App']['RefreshGovernance']();
}

export function ReopenDecision(arg1, arg2) {
  return window['go']['main']['App']['ReopenDecision'](arg1, arg2);
}

export function ResizeTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalSession'](arg1, arg2, arg3);
}

export function ResolveAdoptBaseline(arg1) {
  return window['go']['main']['App']['ResolveAdoptBaseline'](arg1);
}

export function ResolveAdoptDeprecate(arg1, arg2) {
  return window['go']['main']['App']['ResolveAdoptDeprecate'](arg1, arg2);
}

export function ResolveAdoptMeasure(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveAdoptMeasure'](arg1, arg2, arg3);
}

export function ResolveAdoptReopen(arg1, arg2) {
  return window['go']['main']['App']['ResolveAdoptReopen'](arg1, arg2);
}

export function ResolveAdoptWaive(arg1, arg2) {
  return window['go']['main']['App']['ResolveAdoptWaive'](arg1, arg2);
}

export function RunFlowNow(arg1) {
  return window['go']['main']['App']['RunFlowNow'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanForProjects() {
  return window['go']['main']['App']['ScanForProjects']();
}

export function SearchArtifacts(arg1) {
  return window['go']['main']['App']['SearchArtifacts'](arg1);
}

export function SetTaskAutoRun(arg1, arg2) {
  return window['go']['main']['App']['SetTaskAutoRun'](arg1, arg2);
}

export function SpawnTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SpawnTask'](arg1, arg2, arg3, arg4);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function ToggleFlow(arg1, arg2) {
  return window['go']['main']['App']['ToggleFlow'](arg1, arg2);
}

export function UpdateFlow(arg1) {
  return window['go']['main']['App']['UpdateFlow'](arg1);
}

export function VerifyDecision(arg1, arg2) {
  return window['go']['main']['App']['VerifyDecision'](arg1, arg2);
}

export function WaiveDecision(arg1, arg2) {
  return window['go']['main']['App']['WaiveDecision'](arg1, arg2);
}

export function WriteTaskInput(arg1, arg2) {
  return window['go']['main']['App']['WriteTaskInput'](arg1, arg2);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalInput'](arg1, arg2);
}
