// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string):Promise<main.ProjectInfo>;

export function AdoptProblemCandidate(arg1:string):Promise<main.ProblemDetailView>;

export function ArchiveTask(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CharacterizeProblem(arg1:main.ProblemCharacterizationInput):Promise<main.ProblemDetailView>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ComparePortfolio(arg1:main.PortfolioCompareInput):Promise<main.PortfolioDetailView>;

export function CreateDecision(arg1:main.DecisionCreateInput):Promise<main.DecisionDetailView>;

export function CreateFlow(arg1:main.FlowInput):Promise<main.DesktopFlow>;

export function CreatePortfolio(arg1:main.PortfolioCreateInput):Promise<main.PortfolioDetailView>;

export function CreateProblem(arg1:main.ProblemCreateInput):Promise<main.ProblemDetailView>;

export function CreateTerminalSession(arg1:string):Promise<main.TerminalSession>;

export function DeleteFlow(arg1:string):Promise<void>;

export function DetectAgents():Promise<Array<main.InstalledAgent>>;

export function DismissProblemCandidate(arg1:string):Promise<void>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetCoverage():Promise<main.CoverageView>;

export function GetDashboard():Promise<main.DashboardView>;

export function GetDecision(arg1:string):Promise<main.DecisionDetailView>;

export function GetGovernanceOverview():Promise<main.GovernanceOverviewView>;

export function GetPortfolio(arg1:string):Promise<main.PortfolioDetailView>;

export function GetProblem(arg1:string):Promise<main.ProblemDetailView>;

export function GetTaskOutput(arg1:string):Promise<string>;

export function HandoffTask(arg1:string,arg2:string):Promise<main.TaskState>;

export function ImplementDecision(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<main.TaskState>;

export function InitProject(arg1:string):Promise<main.ProjectInfo>;

export function ListAllTasks():Promise<Array<main.TaskState>>;

export function ListDecisions():Promise<Array<main.DecisionView>>;

export function ListFlowTemplates():Promise<Array<main.FlowTemplate>>;

export function ListFlows():Promise<Array<main.DesktopFlow>>;

export function ListPortfolios():Promise<Array<main.PortfolioSummaryView>>;

export function ListProblemCandidates():Promise<Array<main.ProblemCandidateView>>;

export function ListProblems():Promise<Array<main.ProblemView>>;

export function ListProjects():Promise<Array<main.ProjectInfo>>;

export function ListTasks():Promise<Array<main.TaskState>>;

export function ListTerminalSessions():Promise<Array<main.TerminalSession>>;

export function OpenDirectoryPicker():Promise<string>;

export function OpenPathInIDE(arg1:string):Promise<void>;

export function RefreshGovernance():Promise<main.GovernanceOverviewView>;

export function ResizeTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RunFlowNow(arg1:string):Promise<main.TaskState>;

export function SaveConfig(arg1:main.DesktopConfig):Promise<main.DesktopConfig>;

export function ScanForProjects():Promise<Array<main.ProjectInfo>>;

export function SearchArtifacts(arg1:string):Promise<Array<main.ArtifactView>>;

export function SpawnTask(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<main.TaskState>;

export function SwitchProject(arg1:string):Promise<void>;

export function ToggleFlow(arg1:string,arg2:boolean):Promise<main.DesktopFlow>;

export function UpdateFlow(arg1:main.FlowInput):Promise<main.DesktopFlow>;

export function VerifyDecision(arg1:string,arg2:string):Promise<main.TaskState>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
