// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function DetectAgents() {
  return window['go']['main']['App']['DetectAgents']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetDecision(arg1) {
  return window['go']['main']['App']['GetDecision'](arg1);
}

export function GetPortfolio(arg1) {
  return window['go']['main']['App']['GetPortfolio'](arg1);
}

export function GetProblem(arg1) {
  return window['go']['main']['App']['GetProblem'](arg1);
}

export function ImplementDecision(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImplementDecision'](arg1, arg2, arg3, arg4);
}

export function ListDecisions() {
  return window['go']['main']['App']['ListDecisions']();
}

export function ListPortfolios() {
  return window['go']['main']['App']['ListPortfolios']();
}

export function ListProblems() {
  return window['go']['main']['App']['ListProblems']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ScanForProjects() {
  return window['go']['main']['App']['ScanForProjects']();
}

export function SearchArtifacts(arg1) {
  return window['go']['main']['App']['SearchArtifacts'](arg1);
}

export function SpawnTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SpawnTask'](arg1, arg2, arg3, arg4);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function VerifyDecision(arg1, arg2) {
  return window['go']['main']['App']['VerifyDecision'](arg1, arg2);
}
